Update deployment.yaml

diff --git a/gitlab/gitlab-main/gitlab/templates/deployment.yaml b/gitlab/gitlab-main/gitlab/templates/deployment.yaml
--- a/gitlab/gitlab-main/gitlab/templates/deployment.yaml
+++ b/gitlab/gitlab-main/gitlab/templates/deployment.yaml
@@ -22,33 +22,32 @@ spec:
     spec:
       automountServiceAccountToken: false
       securityContext:
-        runAsUser: 998
-        runAsGroup: 998
-        fsGroup: 998
-        runAsNonRoot: true
+        runAsNonRoot: false
         seccompProfile:
           type: RuntimeDefault
       initContainers:
-  - name: fix-permissions
-    image: busybox:1.36
-    command:
-      - /bin/sh
-      - -c
-      - |
-        echo "[INFO] Ensuring directory exists: /var/opt/gitlab";
-        mkdir -p /var/opt/gitlab/backups;
-        chmod -R 775 /var/opt/gitlab || echo "[WARN] Failed to chmod";
-    securityContext:
-      runAsUser: 998
-      runAsGroup: 998
-      allowPrivilegeEscalation: false
-      capabilities:
-        drop:
-          - ALL
-    volumeMounts:
-      - mountPath: /var/opt/gitlab
-        name: gitlab-storage
-
+        - name: fix-permissions
+          image: alpine:3.18
+          command:
+            - /bin/sh
+            - -c
+            - |
+              echo "[INFO] Fixing permissions on /var/opt/gitlab";
+              if [ -d /var/opt/gitlab ]; then
+                chown -R 998:998 /var/opt/gitlab || echo "[WARN] Failed to chown";
+              else
+                echo "[ERROR] Directory /var/opt/gitlab not found!";
+              fi
+          securityContext:
+            runAsUser: 0
+            runAsGroup: 0
+            allowPrivilegeEscalation: false
+            capabilities:
+              drop:
+                - ALL
+          volumeMounts:
+            - mountPath: /var/opt/gitlab
+              name: gitlab-storage
       containers:
         - name: gitlab
           image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
@@ -101,8 +100,8 @@ spec:
             failureThreshold: 3
           securityContext:
             allowPrivilegeEscalation: false
-            readOnlyRootFilesystem: false
-            runAsNonRoot: true
+            readOnlyRootFilesystem: true
+            runAsNonRoot: false
             capabilities:
               drop:
                 - ALL
